---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "../man/figures/README-",
  out.width = 400,
  message = FALSE
)
```

```{r define-z-test-function}
library(dplyr)

ztest <- function(data) {
  data_c <- data |> filter(group == 0L)
  data_t <- data |> filter(group == 1L)
  
  mean_c <- mean(data_c$metric)
  mean_t <- mean(data_t$metric)
  diff <- mean_t - mean_c
  se2_c <- var(data_c$metric)
  se2_t <- var(data_t$metric)
  se <- sqrt(se2_c / nrow(data_c) + se2_t / nrow(data_t))
  z <- diff / se
  p <- 2 * pnorm(-abs(z))
  list(p.value = p)
}
```

```{r p-values-from-z-test, fig.width=4, fig.height=3, cache=TRUE}
library(ggplot2)

n_user <- 2000L

set.seed(314)
p_values <- NULL
for (i in 1:5000) {
  df <- deltatest::generate_dummy_data(n_user)
  
  result <- ztest(df)
  
  p_values[i] <- result$p.value
}

df <- data.frame(p_value = p_values) |>
  mutate(range = cut(p_value, breaks = seq(0, 1, by = 0.05))) |>
  group_by(range) |>
  summarise(p = factor(ceiling(max(p_value) * 20) / 20), n = n()) |>
  mutate(prop = n / sum(n))
ggplot(df, aes(p, prop)) +
  geom_col() +
  geom_hline(yintercept = 0.05, color = "red") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.02), minor_breaks = NULL) +
  xlab("p-value") + ylab("proportion") +
  ggtitle("Standard Z-test for Data with Within-User Correlation") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1), 
        plot.title = element_text(size = 10))
```


```{r p-values-from-delta-method, fig.width=4, fig.height=3, cache=TRUE}
library(deltatest)
library(ggplot2)

n_user <- 2000L

set.seed(314)
p_values <- NULL
for (i in 1:5000) {
  df <- generate_dummy_data(n_user) |> 
    group_by(user_id, group) |> 
    summarise(click = sum(metric), pageview = n(), .groups = "drop")
  
  result <- deltatest(df, click / pageview, by = group)
  
  p_values[i] <- result$p.value
}

df <- data.frame(p_value = p_values) |>
  mutate(range = cut(p_value, breaks = seq(0, 1, by = 0.05))) |>
  group_by(range) |>
  summarise(p = factor(ceiling(max(p_value) * 20) / 20), n = n()) |>
  mutate(prop = n / sum(n))
ggplot(df, aes(p, prop)) +
  geom_col() +
  geom_hline(yintercept = 0.05, color = "red") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.01), minor_breaks = NULL) +
  xlab("p-value") + ylab("proportion") +
  ggtitle("deltatest for Data with Within-User Correlation") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1), 
        plot.title = element_text(size = 10))
```
